#!/bin/bash
set -euo pipefail

# Store PlanetScale credentials in AWS Secrets Manager for SchemaBot.
#
# Reads credentials from .planetscale-credentials (generated by bootstrap-planetscale.sh).
# Flags --token and --vtgate-dsn override the file values.
#
# Usage: cd deploy/aws-multi-env/staging && ../scripts/setup-planetscale-token.sh
#
# Prerequisites:
#   - bootstrap.sh has already run (terraform state exists)
#   - bootstrap-planetscale.sh has been run (creates .planetscale-credentials)
#   - AWS CLI configured with correct region

REGION="${AWS_DEFAULT_REGION:-us-west-2}"
CREDS_FILE=".planetscale-credentials"

# ============================================================================
# Parse flags (optional overrides)
# ============================================================================

TOKEN=""
VTGATE_DSN=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --token)
            TOKEN="$2"
            shift 2
            ;;
        --vtgate-dsn)
            VTGATE_DSN="$2"
            shift 2
            ;;
        --help|-h)
            echo "Store PlanetScale credentials in AWS Secrets Manager"
            echo ""
            echo "Usage: $0"
            echo ""
            echo "Reads credentials from $CREDS_FILE (generated by bootstrap-planetscale.sh)."
            echo ""
            echo "Optional overrides:"
            echo "  --token <id:secret>       Override service token"
            echo "  --vtgate-dsn <dsn>        Override vtgate DSN"
            echo ""
            echo "Run from an environment directory (e.g., staging/) with terraform state."
            exit 0
            ;;
        *)
            echo "Unknown flag: $1"
            exit 1
            ;;
    esac
done

# ============================================================================
# Read credentials from file (if flags not provided)
# ============================================================================

if [ -z "$TOKEN" ] || [ -z "$VTGATE_DSN" ]; then
    # Look for credentials file in current dir, parent dir, or script dir
    if [ -f "$CREDS_FILE" ]; then
        :
    elif [ -f "../$CREDS_FILE" ]; then
        CREDS_FILE="../$CREDS_FILE"
    elif [ -f "$(dirname "$0")/../$CREDS_FILE" ]; then
        CREDS_FILE="$(dirname "$0")/../$CREDS_FILE"
    else
        echo "Error: $CREDS_FILE not found."
        echo "Run bootstrap-planetscale.sh first, or pass --token and --vtgate-dsn flags."
        exit 1
    fi
    # Source the file to get TOKEN and VTGATE_DSN
    # shellcheck source=/dev/null
    source "$CREDS_FILE"
    if [ -z "$TOKEN" ] || [ -z "$VTGATE_DSN" ]; then
        echo "Error: $CREDS_FILE is missing TOKEN or VTGATE_DSN."
        exit 1
    fi
fi

# ============================================================================
# Derive prefix from terraform output
# ============================================================================

TF_OUTPUT=$(terraform output -json 2>/dev/null || echo '{}')
PREFIX=$(echo "$TF_OUTPUT" | jq -r '.storage_dsn_secret_id.value // empty' | sed 's|/storage-dsn||')
if [ -z "$PREFIX" ]; then
    echo "Error: could not determine prefix from terraform output."
    echo "Run from the environment directory (e.g., staging/)."
    exit 1
fi

echo "🔑 PlanetScale Credentials Setup"
echo "================================="
echo "  Region: $REGION"
echo "  Prefix: $PREFIX"
echo ""

# ============================================================================
# Create or update secrets
# ============================================================================

create_or_update_secret() {
    local secret_id="$1"
    local secret_value="$2"
    local description="$3"

    if aws secretsmanager describe-secret --region "$REGION" --secret-id "$secret_id" > /dev/null 2>&1; then
        echo "  Updating existing secret: $secret_id"
        aws secretsmanager update-secret \
            --region "$REGION" \
            --secret-id "$secret_id" \
            --secret-string "$secret_value" > /dev/null
    else
        echo "  Creating secret: $secret_id"
        aws secretsmanager create-secret \
            --region "$REGION" \
            --name "$secret_id" \
            --description "$description" \
            --secret-string "$secret_value" > /dev/null
    fi
}

# Service token
TOKEN_SECRET_ID="$PREFIX/planetscale-token"
TOKEN_VALUE=$(jq -n --arg token "$TOKEN" '{"token": $token}')
create_or_update_secret "$TOKEN_SECRET_ID" "$TOKEN_VALUE" "PlanetScale service token for SchemaBot"
echo "  ✓ Service token stored"
echo ""

# Vtgate DSN
VTGATE_SECRET_ID="$PREFIX/planetscale-vtgate"
VTGATE_VALUE=$(jq -n --arg dsn "$VTGATE_DSN" '{"dsn": $dsn}')
create_or_update_secret "$VTGATE_SECRET_ID" "$VTGATE_VALUE" "PlanetScale vtgate credentials for SchemaBot"
echo "  ✓ Vtgate DSN stored"
echo ""

echo "Done. Secrets stored:"
echo "  - $TOKEN_SECRET_ID"
echo "  - $VTGATE_SECRET_ID"
echo ""
echo "Config references:"
echo "  token_secret_ref: \"secretsmanager:$TOKEN_SECRET_ID#token\""
echo "  dsn: \"secretsmanager:$VTGATE_SECRET_ID#dsn\""
