CREATE TABLE `localscale_deploy_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `number` bigint unsigned NOT NULL,
  `org` varchar(255) NOT NULL DEFAULT '',
  `database_name` varchar(255) NOT NULL DEFAULT '',
  `token_name` varchar(255) NOT NULL DEFAULT '',
  `branch` varchar(255) NOT NULL,
  `into_branch` varchar(255) NOT NULL DEFAULT 'main',
  `auto_cutover` tinyint(1) NOT NULL DEFAULT '0',
  `ddl_statements` text,
  `vschema_data` text,
  `vschema_applied` tinyint(1) NOT NULL DEFAULT '0',
  `vschema_data_original` text,
  `vschema_reverted` tinyint(1) NOT NULL DEFAULT '0',
  `migration_context` varchar(255) NOT NULL DEFAULT '',
  `revert_migration_context` varchar(255) NOT NULL DEFAULT '',
  `deployment_state` varchar(50) NOT NULL DEFAULT 'pending',
  `deployed` tinyint(1) NOT NULL DEFAULT '0',
  `cutover_requested` tinyint(1) NOT NULL DEFAULT '0',
  `cancelled` tinyint(1) NOT NULL DEFAULT '0',
  `reverted` tinyint(1) NOT NULL DEFAULT '0',
  `revert_skipped` tinyint(1) NOT NULL DEFAULT '0',
  `throttle_ratio` double NOT NULL DEFAULT '0',
  `schema_before` mediumtext,
  `instant_ddl_eligible` tinyint(1) NOT NULL DEFAULT '0',
  `instant_ddl` tinyint(1) NOT NULL DEFAULT '0',
  `revert_expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_database_number` (`org`,`database_name`,`number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
