// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tern.proto

package ternv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Engine represents the schema change engine type.
type Engine int32

const (
	Engine_ENGINE_SPIRIT      Engine = 0
	Engine_ENGINE_PLANETSCALE Engine = 1
)

// Enum value maps for Engine.
var (
	Engine_name = map[int32]string{
		0: "ENGINE_SPIRIT",
		1: "ENGINE_PLANETSCALE",
	}
	Engine_value = map[string]int32{
		"ENGINE_SPIRIT":      0,
		"ENGINE_PLANETSCALE": 1,
	}
)

func (x Engine) Enum() *Engine {
	p := new(Engine)
	*p = x
	return p
}

func (x Engine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Engine) Descriptor() protoreflect.EnumDescriptor {
	return file_tern_proto_enumTypes[0].Descriptor()
}

func (Engine) Type() protoreflect.EnumType {
	return &file_tern_proto_enumTypes[0]
}

func (x Engine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Engine.Descriptor instead.
func (Engine) EnumDescriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{0}
}

// State represents the state of a schema change task.
type State int32

const (
	State_STATE_NO_ACTIVE_CHANGE          State = 0
	State_STATE_PENDING                   State = 1
	State_STATE_RUNNING                   State = 2
	State_STATE_WAITING_FOR_CUTOVER       State = 3
	State_STATE_CUTTING_OVER              State = 4
	State_STATE_REVERT_WINDOW             State = 5
	State_STATE_COMPLETED                 State = 6
	State_STATE_FAILED                    State = 7
	State_STATE_STOPPED                   State = 8
	State_STATE_REVERTED                  State = 9
	State_STATE_CANCELLED                 State = 10
	State_STATE_PREPARING_BRANCH          State = 11
	State_STATE_APPLYING_BRANCH_CHANGES   State = 12
	State_STATE_CREATING_DEPLOY_REQUEST   State = 13
	State_STATE_WAITING_FOR_DEPLOY        State = 14
	State_STATE_VALIDATING_DEPLOY_REQUEST State = 15
	State_STATE_VALIDATING_BRANCH         State = 16
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0:  "STATE_NO_ACTIVE_CHANGE",
		1:  "STATE_PENDING",
		2:  "STATE_RUNNING",
		3:  "STATE_WAITING_FOR_CUTOVER",
		4:  "STATE_CUTTING_OVER",
		5:  "STATE_REVERT_WINDOW",
		6:  "STATE_COMPLETED",
		7:  "STATE_FAILED",
		8:  "STATE_STOPPED",
		9:  "STATE_REVERTED",
		10: "STATE_CANCELLED",
		11: "STATE_PREPARING_BRANCH",
		12: "STATE_APPLYING_BRANCH_CHANGES",
		13: "STATE_CREATING_DEPLOY_REQUEST",
		14: "STATE_WAITING_FOR_DEPLOY",
		15: "STATE_VALIDATING_DEPLOY_REQUEST",
		16: "STATE_VALIDATING_BRANCH",
	}
	State_value = map[string]int32{
		"STATE_NO_ACTIVE_CHANGE":          0,
		"STATE_PENDING":                   1,
		"STATE_RUNNING":                   2,
		"STATE_WAITING_FOR_CUTOVER":       3,
		"STATE_CUTTING_OVER":              4,
		"STATE_REVERT_WINDOW":             5,
		"STATE_COMPLETED":                 6,
		"STATE_FAILED":                    7,
		"STATE_STOPPED":                   8,
		"STATE_REVERTED":                  9,
		"STATE_CANCELLED":                 10,
		"STATE_PREPARING_BRANCH":          11,
		"STATE_APPLYING_BRANCH_CHANGES":   12,
		"STATE_CREATING_DEPLOY_REQUEST":   13,
		"STATE_WAITING_FOR_DEPLOY":        14,
		"STATE_VALIDATING_DEPLOY_REQUEST": 15,
		"STATE_VALIDATING_BRANCH":         16,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_tern_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_tern_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{1}
}

// ChangeType represents the type of schema change.
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_OTHER   ChangeType = 0
	ChangeType_CHANGE_TYPE_CREATE  ChangeType = 1
	ChangeType_CHANGE_TYPE_ALTER   ChangeType = 2
	ChangeType_CHANGE_TYPE_DROP    ChangeType = 3
	ChangeType_CHANGE_TYPE_VSCHEMA ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_OTHER",
		1: "CHANGE_TYPE_CREATE",
		2: "CHANGE_TYPE_ALTER",
		3: "CHANGE_TYPE_DROP",
		4: "CHANGE_TYPE_VSCHEMA",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_OTHER":   0,
		"CHANGE_TYPE_CREATE":  1,
		"CHANGE_TYPE_ALTER":   2,
		"CHANGE_TYPE_DROP":    3,
		"CHANGE_TYPE_VSCHEMA": 4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_tern_proto_enumTypes[2].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_tern_proto_enumTypes[2]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{2}
}

// SchemaFiles contains the schema files for a namespace (e.g. schema name for MySQL, keyspace for Vitess).
type SchemaFiles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filename → content mapping (e.g., "users.sql" → CREATE TABLE, "vschema.json" → VSchema JSON).
	Files         map[string]string `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaFiles) Reset() {
	*x = SchemaFiles{}
	mi := &file_tern_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaFiles) ProtoMessage() {}

func (x *SchemaFiles) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaFiles.ProtoReflect.Descriptor instead.
func (*SchemaFiles) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaFiles) GetFiles() map[string]string {
	if x != nil {
		return x.Files
	}
	return nil
}

// PlanRequest requests a schema change plan from declarative schema files.
type PlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Database name (e.g., "banklin"). Used for database discovery and connection lookup.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql".
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Schema files per namespace (e.g. schema name for MySQL, keyspace for Vitess).
	SchemaFiles map[string]*SchemaFiles `protobuf:"bytes,3,rep,name=schema_files,json=schemaFiles,proto3" json:"schema_files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Source repository (e.g., "org/repo").
	Repository string `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	// Source pull request number.
	PullRequest int32 `protobuf:"varint,5,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	// Opaque identifier for endpoint discovery (e.g., database identifier).
	// Forwarded to Tern for provider-based resolution. Defaults to database if empty.
	Target string `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	// PR HEAD SHA at the time schema files were discovered. Persisted on the
	// stored plan record so apply-confirm can detect the cross-delivery race
	// where HEAD advances between the plan being posted and the user clicking
	// apply-confirm. Empty for non-webhook callers (e.g. CLI plan invocations
	// without a PR context).
	HeadSha string `protobuf:"bytes,9,opt,name=head_sha,json=headSha,proto3" json:"head_sha,omitempty"`
	// Repo-relative schema directory discovered by SchemaBot from the PR.
	SchemaPath    string `protobuf:"bytes,10,opt,name=schema_path,json=schemaPath,proto3" json:"schema_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_tern_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{1}
}

func (x *PlanRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *PlanRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlanRequest) GetSchemaFiles() map[string]*SchemaFiles {
	if x != nil {
		return x.SchemaFiles
	}
	return nil
}

func (x *PlanRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *PlanRequest) GetPullRequest() int32 {
	if x != nil {
		return x.PullRequest
	}
	return 0
}

func (x *PlanRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *PlanRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PlanRequest) GetHeadSha() string {
	if x != nil {
		return x.HeadSha
	}
	return ""
}

func (x *PlanRequest) GetSchemaPath() string {
	if x != nil {
		return x.SchemaPath
	}
	return ""
}

// TableChange represents a DDL change to a table.
type TableChange struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TableName  string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Ddl        string                 `protobuf:"bytes,2,opt,name=ddl,proto3" json:"ddl,omitempty"`
	ChangeType ChangeType             `protobuf:"varint,3,opt,name=change_type,json=changeType,proto3,enum=tern.v1.ChangeType" json:"change_type,omitempty"`
	Namespace  string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Unsafe change tracking
	IsUnsafe      bool   `protobuf:"varint,5,opt,name=is_unsafe,json=isUnsafe,proto3" json:"is_unsafe,omitempty"`
	UnsafeReason  string `protobuf:"bytes,6,opt,name=unsafe_reason,json=unsafeReason,proto3" json:"unsafe_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableChange) Reset() {
	*x = TableChange{}
	mi := &file_tern_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableChange) ProtoMessage() {}

func (x *TableChange) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableChange.ProtoReflect.Descriptor instead.
func (*TableChange) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{2}
}

func (x *TableChange) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableChange) GetDdl() string {
	if x != nil {
		return x.Ddl
	}
	return ""
}

func (x *TableChange) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_OTHER
}

func (x *TableChange) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TableChange) GetIsUnsafe() bool {
	if x != nil {
		return x.IsUnsafe
	}
	return false
}

func (x *TableChange) GetUnsafeReason() string {
	if x != nil {
		return x.UnsafeReason
	}
	return ""
}

// SchemaChange groups all changes for a single namespace (keyspace/schema).
type SchemaChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TableChanges  []*TableChange         `protobuf:"bytes,2,rep,name=table_changes,json=tableChanges,proto3" json:"table_changes,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Engine-specific data (e.g., "vschema" → diff)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaChange) Reset() {
	*x = SchemaChange{}
	mi := &file_tern_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaChange) ProtoMessage() {}

func (x *SchemaChange) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaChange.ProtoReflect.Descriptor instead.
func (*SchemaChange) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{3}
}

func (x *SchemaChange) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SchemaChange) GetTableChanges() []*TableChange {
	if x != nil {
		return x.TableChanges
	}
	return nil
}

func (x *SchemaChange) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// LintViolation represents a schema linting violation.
// Violations with severity "error" block apply unless --allow-unsafe is passed.
type LintViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Column        string                 `protobuf:"bytes,3,opt,name=column,proto3" json:"column,omitempty"`
	Linter        string                 `protobuf:"bytes,4,opt,name=linter,proto3" json:"linter,omitempty"`
	FixType       string                 `protobuf:"bytes,5,opt,name=fix_type,json=fixType,proto3" json:"fix_type,omitempty"`
	Severity      string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"` // "error", "warning", or "info"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintViolation) Reset() {
	*x = LintViolation{}
	mi := &file_tern_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintViolation) ProtoMessage() {}

func (x *LintViolation) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintViolation.ProtoReflect.Descriptor instead.
func (*LintViolation) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{4}
}

func (x *LintViolation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LintViolation) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *LintViolation) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *LintViolation) GetLinter() string {
	if x != nil {
		return x.Linter
	}
	return ""
}

func (x *LintViolation) GetFixType() string {
	if x != nil {
		return x.FixType
	}
	return ""
}

func (x *LintViolation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

// PlanResponse contains the generated schema change plan.
// Lint violations with severity "error" block apply unless --allow-unsafe.
type PlanResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlanId         string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Engine         Engine                 `protobuf:"varint,2,opt,name=engine,proto3,enum=tern.v1.Engine" json:"engine,omitempty"`
	Changes        []*SchemaChange        `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	LintViolations []*LintViolation       `protobuf:"bytes,4,rep,name=lint_violations,json=lintViolations,proto3" json:"lint_violations,omitempty"`
	Errors         []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_tern_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{5}
}

func (x *PlanResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanResponse) GetEngine() Engine {
	if x != nil {
		return x.Engine
	}
	return Engine_ENGINE_SPIRIT
}

func (x *PlanResponse) GetChanges() []*SchemaChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *PlanResponse) GetLintViolations() []*LintViolation {
	if x != nil {
		return x.LintViolations
	}
	return nil
}

func (x *PlanResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// ApplyRequest requests execution of a previously generated plan.
// DDL changes are passed by the caller since clients are stateless.
type ApplyRequest struct {
	state       protoimpl.MessageState  `protogen:"open.v1"`
	PlanId      string                  `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Options     map[string]string       `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SchemaFiles map[string]*SchemaFiles `protobuf:"bytes,3,rep,name=schema_files,json=schemaFiles,proto3" json:"schema_files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Database name for the apply operation.
	Database string `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql".
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// DDL changes from PlanStore (clients are stateless and don't store plans).
	DdlChanges []*TableChange `protobuf:"bytes,6,rep,name=ddl_changes,json=ddlChanges,proto3" json:"ddl_changes,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,7,opt,name=environment,proto3" json:"environment,omitempty"`
	// Opaque identifier for endpoint discovery (e.g., database identifier).
	// Forwarded to Tern for provider-based resolution. Defaults to database if empty.
	Target string `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	// Caller identity (e.g., "cli:user@hostname", "webhook:repo#pr").
	Caller        string `protobuf:"bytes,9,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_tern_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ApplyRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ApplyRequest) GetSchemaFiles() map[string]*SchemaFiles {
	if x != nil {
		return x.SchemaFiles
	}
	return nil
}

func (x *ApplyRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ApplyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApplyRequest) GetDdlChanges() []*TableChange {
	if x != nil {
		return x.DdlChanges
	}
	return nil
}

func (x *ApplyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ApplyRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ApplyRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

// ApplyResponse indicates whether the apply was accepted.
type ApplyResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Accepted     bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// The apply identifier for tracking this schema change.
	ApplyId       string `protobuf:"bytes,3,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_tern_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ApplyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ApplyResponse) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

// ProgressRequest requests detailed progress for an active schema change.
type ProgressRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql". Used by stateless clients.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Optional: scope progress to a specific apply ID.
	// If empty, returns progress for the active schema change.
	ApplyId       string `protobuf:"bytes,4,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_tern_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{8}
}

func (x *ProgressRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ProgressRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProgressRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ProgressRequest) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

// ShardProgress contains progress information for a single Vitess shard.
type ShardProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Shard              string                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RowsCopied         int64                  `protobuf:"varint,3,opt,name=rows_copied,json=rowsCopied,proto3" json:"rows_copied,omitempty"`
	RowsTotal          int64                  `protobuf:"varint,4,opt,name=rows_total,json=rowsTotal,proto3" json:"rows_total,omitempty"`
	EtaSeconds         int64                  `protobuf:"varint,5,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	CutoverAttempts    int32                  `protobuf:"varint,6,opt,name=cutover_attempts,json=cutoverAttempts,proto3" json:"cutover_attempts,omitempty"`
	LastCutoverAttempt string                 `protobuf:"bytes,7,opt,name=last_cutover_attempt,json=lastCutoverAttempt,proto3" json:"last_cutover_attempt,omitempty"`
	ReadyToComplete    bool                   `protobuf:"varint,8,opt,name=ready_to_complete,json=readyToComplete,proto3" json:"ready_to_complete,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ShardProgress) Reset() {
	*x = ShardProgress{}
	mi := &file_tern_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardProgress) ProtoMessage() {}

func (x *ShardProgress) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardProgress.ProtoReflect.Descriptor instead.
func (*ShardProgress) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{9}
}

func (x *ShardProgress) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *ShardProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShardProgress) GetRowsCopied() int64 {
	if x != nil {
		return x.RowsCopied
	}
	return 0
}

func (x *ShardProgress) GetRowsTotal() int64 {
	if x != nil {
		return x.RowsTotal
	}
	return 0
}

func (x *ShardProgress) GetEtaSeconds() int64 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

func (x *ShardProgress) GetCutoverAttempts() int32 {
	if x != nil {
		return x.CutoverAttempts
	}
	return 0
}

func (x *ShardProgress) GetLastCutoverAttempt() string {
	if x != nil {
		return x.LastCutoverAttempt
	}
	return ""
}

func (x *ShardProgress) GetReadyToComplete() bool {
	if x != nil {
		return x.ReadyToComplete
	}
	return false
}

// TableProgress contains progress information for a single table.
type TableProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TableName       string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Ddl             string                 `protobuf:"bytes,4,opt,name=ddl,proto3" json:"ddl,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RowsCopied      int64                  `protobuf:"varint,6,opt,name=rows_copied,json=rowsCopied,proto3" json:"rows_copied,omitempty"`
	RowsTotal       int64                  `protobuf:"varint,7,opt,name=rows_total,json=rowsTotal,proto3" json:"rows_total,omitempty"`
	PercentComplete int32                  `protobuf:"varint,8,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"`
	EtaSeconds      int64                  `protobuf:"varint,9,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	IsInstant       bool                   `protobuf:"varint,10,opt,name=is_instant,json=isInstant,proto3" json:"is_instant,omitempty"`
	Shards          []*ShardProgress       `protobuf:"bytes,11,rep,name=shards,proto3" json:"shards,omitempty"`
	ProgressDetail  string                 `protobuf:"bytes,12,opt,name=progress_detail,json=progressDetail,proto3" json:"progress_detail,omitempty"`
	ChangeType      ChangeType             `protobuf:"varint,13,opt,name=change_type,json=changeType,proto3,enum=tern.v1.ChangeType" json:"change_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TableProgress) Reset() {
	*x = TableProgress{}
	mi := &file_tern_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableProgress) ProtoMessage() {}

func (x *TableProgress) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableProgress.ProtoReflect.Descriptor instead.
func (*TableProgress) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{10}
}

func (x *TableProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TableProgress) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TableProgress) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableProgress) GetDdl() string {
	if x != nil {
		return x.Ddl
	}
	return ""
}

func (x *TableProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TableProgress) GetRowsCopied() int64 {
	if x != nil {
		return x.RowsCopied
	}
	return 0
}

func (x *TableProgress) GetRowsTotal() int64 {
	if x != nil {
		return x.RowsTotal
	}
	return 0
}

func (x *TableProgress) GetPercentComplete() int32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

func (x *TableProgress) GetEtaSeconds() int64 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

func (x *TableProgress) GetIsInstant() bool {
	if x != nil {
		return x.IsInstant
	}
	return false
}

func (x *TableProgress) GetShards() []*ShardProgress {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *TableProgress) GetProgressDetail() string {
	if x != nil {
		return x.ProgressDetail
	}
	return ""
}

func (x *TableProgress) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_OTHER
}

// ProgressResponse contains detailed progress information.
type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       string                 `protobuf:"bytes,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	State         State                  `protobuf:"varint,2,opt,name=state,proto3,enum=tern.v1.State" json:"state,omitempty"`
	Engine        Engine                 `protobuf:"varint,3,opt,name=engine,proto3,enum=tern.v1.Engine" json:"engine,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Tables        []*TableProgress       `protobuf:"bytes,6,rep,name=tables,proto3" json:"tables,omitempty"`
	StartedAt     string                 `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Volume        int32                  `protobuf:"varint,9,opt,name=volume,proto3" json:"volume,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_tern_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{11}
}

func (x *ProgressResponse) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

func (x *ProgressResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_NO_ACTIVE_CHANGE
}

func (x *ProgressResponse) GetEngine() Engine {
	if x != nil {
		return x.Engine
	}
	return Engine_ENGINE_SPIRIT
}

func (x *ProgressResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ProgressResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProgressResponse) GetTables() []*TableProgress {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *ProgressResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ProgressResponse) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *ProgressResponse) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *ProgressResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CutoverRequest triggers the cutover phase.
type CutoverRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql". Used by stateless clients.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Scope cutover to a specific apply ID.
	ApplyId       string `protobuf:"bytes,4,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutoverRequest) Reset() {
	*x = CutoverRequest{}
	mi := &file_tern_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutoverRequest) ProtoMessage() {}

func (x *CutoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutoverRequest.ProtoReflect.Descriptor instead.
func (*CutoverRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{12}
}

func (x *CutoverRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *CutoverRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CutoverRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *CutoverRequest) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

// CutoverResponse indicates whether the cutover was accepted.
type CutoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutoverResponse) Reset() {
	*x = CutoverResponse{}
	mi := &file_tern_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutoverResponse) ProtoMessage() {}

func (x *CutoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutoverResponse.ProtoReflect.Descriptor instead.
func (*CutoverResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{13}
}

func (x *CutoverResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CutoverResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RevertRequest reverts a completed schema change.
type RevertRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql". Used by stateless clients.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Scope revert to a specific apply ID.
	ApplyId       string `protobuf:"bytes,4,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertRequest) Reset() {
	*x = RevertRequest{}
	mi := &file_tern_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertRequest) ProtoMessage() {}

func (x *RevertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertRequest.ProtoReflect.Descriptor instead.
func (*RevertRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{14}
}

func (x *RevertRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *RevertRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RevertRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RevertRequest) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

// RevertResponse indicates whether the revert was accepted.
type RevertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertResponse) Reset() {
	*x = RevertResponse{}
	mi := &file_tern_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertResponse) ProtoMessage() {}

func (x *RevertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertResponse.ProtoReflect.Descriptor instead.
func (*RevertResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{15}
}

func (x *RevertResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RevertResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// SkipRevertRequest skips the revert window.
type SkipRevertRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql". Used by stateless clients.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Scope skip-revert to a specific apply ID.
	ApplyId       string `protobuf:"bytes,4,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipRevertRequest) Reset() {
	*x = SkipRevertRequest{}
	mi := &file_tern_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipRevertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipRevertRequest) ProtoMessage() {}

func (x *SkipRevertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipRevertRequest.ProtoReflect.Descriptor instead.
func (*SkipRevertRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{16}
}

func (x *SkipRevertRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SkipRevertRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SkipRevertRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SkipRevertRequest) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

// SkipRevertResponse indicates whether the skip was accepted.
type SkipRevertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipRevertResponse) Reset() {
	*x = SkipRevertResponse{}
	mi := &file_tern_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipRevertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipRevertResponse) ProtoMessage() {}

func (x *SkipRevertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipRevertResponse.ProtoReflect.Descriptor instead.
func (*SkipRevertResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{17}
}

func (x *SkipRevertResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SkipRevertResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HealthRequest is the health check request.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_tern_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{18}
}

// HealthResponse is the health check response.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_tern_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{19}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// StopRequest pauses in-progress schema changes for a database.
type StopRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql". Used by stateless clients.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Scope stop to a specific apply ID.
	ApplyId       string `protobuf:"bytes,4,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_tern_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{20}
}

func (x *StopRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *StopRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StopRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *StopRequest) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

// StopResponse indicates whether the stop was accepted.
type StopResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Accepted     bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// For MySQL: time remaining before binlog expires and resume becomes impossible.
	ResumeDeadline string `protobuf:"bytes,3,opt,name=resume_deadline,json=resumeDeadline,proto3" json:"resume_deadline,omitempty"`
	// Number of tasks that were stopped.
	StoppedCount int64 `protobuf:"varint,4,opt,name=stopped_count,json=stoppedCount,proto3" json:"stopped_count,omitempty"`
	// Number of tasks skipped (already in terminal state).
	SkippedCount  int64 `protobuf:"varint,5,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_tern_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{21}
}

func (x *StopResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StopResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StopResponse) GetResumeDeadline() string {
	if x != nil {
		return x.ResumeDeadline
	}
	return ""
}

func (x *StopResponse) GetStoppedCount() int64 {
	if x != nil {
		return x.StoppedCount
	}
	return 0
}

func (x *StopResponse) GetSkippedCount() int64 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

// StartRequest resumes stopped schema changes for a database.
type StartRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql". Used by stateless clients.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Scope start to a specific apply ID.
	ApplyId       string `protobuf:"bytes,4,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_tern_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{22}
}

func (x *StartRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *StartRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StartRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *StartRequest) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

// StartResponse indicates whether the start was accepted.
type StartResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Accepted     bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Number of tasks that were started.
	StartedCount int64 `protobuf:"varint,3,opt,name=started_count,json=startedCount,proto3" json:"started_count,omitempty"`
	// Number of tasks skipped (not in stopped state).
	SkippedCount  int64 `protobuf:"varint,4,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_tern_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{23}
}

func (x *StartResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StartResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StartResponse) GetStartedCount() int64 {
	if x != nil {
		return x.StartedCount
	}
	return 0
}

func (x *StartResponse) GetSkippedCount() int64 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

// VolumeRequest modifies the schema change speed/concurrency.
type VolumeRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Database type: "vitess" or "mysql". Used by stateless clients.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Environment: "staging" or "production".
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Volume level 1-11 (1=conservative, 11=aggressive).
	Volume int32 `protobuf:"varint,4,opt,name=volume,proto3" json:"volume,omitempty"`
	// Scope volume change to a specific apply ID.
	ApplyId       string `protobuf:"bytes,5,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeRequest) Reset() {
	*x = VolumeRequest{}
	mi := &file_tern_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRequest) ProtoMessage() {}

func (x *VolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRequest.ProtoReflect.Descriptor instead.
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{24}
}

func (x *VolumeRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *VolumeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VolumeRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *VolumeRequest) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *VolumeRequest) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

// VolumeResponse indicates whether the volume change was accepted.
type VolumeResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Accepted     bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Previous volume level.
	PreviousVolume int32 `protobuf:"varint,3,opt,name=previous_volume,json=previousVolume,proto3" json:"previous_volume,omitempty"`
	// New volume level.
	NewVolume     int32 `protobuf:"varint,4,opt,name=new_volume,json=newVolume,proto3" json:"new_volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeResponse) Reset() {
	*x = VolumeResponse{}
	mi := &file_tern_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeResponse) ProtoMessage() {}

func (x *VolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tern_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeResponse.ProtoReflect.Descriptor instead.
func (*VolumeResponse) Descriptor() ([]byte, []int) {
	return file_tern_proto_rawDescGZIP(), []int{25}
}

func (x *VolumeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *VolumeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VolumeResponse) GetPreviousVolume() int32 {
	if x != nil {
		return x.PreviousVolume
	}
	return 0
}

func (x *VolumeResponse) GetNewVolume() int32 {
	if x != nil {
		return x.NewVolume
	}
	return 0
}

var File_tern_proto protoreflect.FileDescriptor

const file_tern_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tern.proto\x12\atern.v1\x1a\x1cgoogle/api/annotations.proto\"~\n" +
	"\vSchemaFiles\x125\n" +
	"\x05files\x18\x01 \x03(\v2\x1f.tern.v1.SchemaFiles.FilesEntryR\x05files\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x03\n" +
	"\vPlanRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12H\n" +
	"\fschema_files\x18\x03 \x03(\v2%.tern.v1.PlanRequest.SchemaFilesEntryR\vschemaFiles\x12\x1e\n" +
	"\n" +
	"repository\x18\x04 \x01(\tR\n" +
	"repository\x12!\n" +
	"\fpull_request\x18\x05 \x01(\x05R\vpullRequest\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x12\x19\n" +
	"\bhead_sha\x18\t \x01(\tR\aheadSha\x12\x1f\n" +
	"\vschema_path\x18\n \x01(\tR\n" +
	"schemaPath\x1aT\n" +
	"\x10SchemaFilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.tern.v1.SchemaFilesR\x05value:\x028\x01J\x04\b\a\x10\b\"\xd4\x01\n" +
	"\vTableChange\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x10\n" +
	"\x03ddl\x18\x02 \x01(\tR\x03ddl\x124\n" +
	"\vchange_type\x18\x03 \x01(\x0e2\x13.tern.v1.ChangeTypeR\n" +
	"changeType\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tis_unsafe\x18\x05 \x01(\bR\bisUnsafe\x12#\n" +
	"\runsafe_reason\x18\x06 \x01(\tR\funsafeReason\"\xe5\x01\n" +
	"\fSchemaChange\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x129\n" +
	"\rtable_changes\x18\x02 \x03(\v2\x14.tern.v1.TableChangeR\ftableChanges\x12?\n" +
	"\bmetadata\x18\x03 \x03(\v2#.tern.v1.SchemaChange.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\rLintViolation\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x16\n" +
	"\x06column\x18\x03 \x01(\tR\x06column\x12\x16\n" +
	"\x06linter\x18\x04 \x01(\tR\x06linter\x12\x19\n" +
	"\bfix_type\x18\x05 \x01(\tR\afixType\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\"\xda\x01\n" +
	"\fPlanResponse\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12'\n" +
	"\x06engine\x18\x02 \x01(\x0e2\x0f.tern.v1.EngineR\x06engine\x12/\n" +
	"\achanges\x18\x03 \x03(\v2\x15.tern.v1.SchemaChangeR\achanges\x12?\n" +
	"\x0flint_violations\x18\x04 \x03(\v2\x16.tern.v1.LintViolationR\x0elintViolations\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\"\xfb\x03\n" +
	"\fApplyRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12<\n" +
	"\aoptions\x18\x02 \x03(\v2\".tern.v1.ApplyRequest.OptionsEntryR\aoptions\x12I\n" +
	"\fschema_files\x18\x03 \x03(\v2&.tern.v1.ApplyRequest.SchemaFilesEntryR\vschemaFiles\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x125\n" +
	"\vddl_changes\x18\x06 \x03(\v2\x14.tern.v1.TableChangeR\n" +
	"ddlChanges\x12 \n" +
	"\venvironment\x18\a \x01(\tR\venvironment\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x12\x16\n" +
	"\x06caller\x18\t \x01(\tR\x06caller\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aT\n" +
	"\x10SchemaFilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.tern.v1.SchemaFilesR\x05value:\x028\x01\"k\n" +
	"\rApplyResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bapply_id\x18\x03 \x01(\tR\aapplyId\"~\n" +
	"\x0fProgressRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x19\n" +
	"\bapply_id\x18\x04 \x01(\tR\aapplyId\"\xa7\x02\n" +
	"\rShardProgress\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\tR\x05shard\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vrows_copied\x18\x03 \x01(\x03R\n" +
	"rowsCopied\x12\x1d\n" +
	"\n" +
	"rows_total\x18\x04 \x01(\x03R\trowsTotal\x12\x1f\n" +
	"\veta_seconds\x18\x05 \x01(\x03R\n" +
	"etaSeconds\x12)\n" +
	"\x10cutover_attempts\x18\x06 \x01(\x05R\x0fcutoverAttempts\x120\n" +
	"\x14last_cutover_attempt\x18\a \x01(\tR\x12lastCutoverAttempt\x12*\n" +
	"\x11ready_to_complete\x18\b \x01(\bR\x0freadyToComplete\"\xc9\x03\n" +
	"\rTableProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12\x10\n" +
	"\x03ddl\x18\x04 \x01(\tR\x03ddl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vrows_copied\x18\x06 \x01(\x03R\n" +
	"rowsCopied\x12\x1d\n" +
	"\n" +
	"rows_total\x18\a \x01(\x03R\trowsTotal\x12)\n" +
	"\x10percent_complete\x18\b \x01(\x05R\x0fpercentComplete\x12\x1f\n" +
	"\veta_seconds\x18\t \x01(\x03R\n" +
	"etaSeconds\x12\x1d\n" +
	"\n" +
	"is_instant\x18\n" +
	" \x01(\bR\tisInstant\x12.\n" +
	"\x06shards\x18\v \x03(\v2\x16.tern.v1.ShardProgressR\x06shards\x12'\n" +
	"\x0fprogress_detail\x18\f \x01(\tR\x0eprogressDetail\x124\n" +
	"\vchange_type\x18\r \x01(\x0e2\x13.tern.v1.ChangeTypeR\n" +
	"changeType\"\xc7\x03\n" +
	"\x10ProgressResponse\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\tR\aapplyId\x12$\n" +
	"\x05state\x18\x02 \x01(\x0e2\x0e.tern.v1.StateR\x05state\x12'\n" +
	"\x06engine\x18\x03 \x01(\x0e2\x0f.tern.v1.EngineR\x06engine\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12.\n" +
	"\x06tables\x18\x06 \x03(\v2\x16.tern.v1.TableProgressR\x06tables\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\tR\vcompletedAt\x12\x16\n" +
	"\x06volume\x18\t \x01(\x05R\x06volume\x12C\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2'.tern.v1.ProgressResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x0eCutoverRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x19\n" +
	"\bapply_id\x18\x04 \x01(\tR\aapplyId\"R\n" +
	"\x0fCutoverResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"|\n" +
	"\rRevertRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x19\n" +
	"\bapply_id\x18\x04 \x01(\tR\aapplyId\"Q\n" +
	"\x0eRevertResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x80\x01\n" +
	"\x11SkipRevertRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x19\n" +
	"\bapply_id\x18\x04 \x01(\tR\aapplyId\"U\n" +
	"\x12SkipRevertResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"z\n" +
	"\vStopRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x19\n" +
	"\bapply_id\x18\x04 \x01(\tR\aapplyId\"\xc2\x01\n" +
	"\fStopResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fresume_deadline\x18\x03 \x01(\tR\x0eresumeDeadline\x12#\n" +
	"\rstopped_count\x18\x04 \x01(\x03R\fstoppedCount\x12#\n" +
	"\rskipped_count\x18\x05 \x01(\x03R\fskippedCount\"{\n" +
	"\fStartRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x19\n" +
	"\bapply_id\x18\x04 \x01(\tR\aapplyId\"\x9a\x01\n" +
	"\rStartResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rstarted_count\x18\x03 \x01(\x03R\fstartedCount\x12#\n" +
	"\rskipped_count\x18\x04 \x01(\x03R\fskippedCount\"\x94\x01\n" +
	"\rVolumeRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x05R\x06volume\x12\x19\n" +
	"\bapply_id\x18\x05 \x01(\tR\aapplyId\"\x99\x01\n" +
	"\x0eVolumeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fprevious_volume\x18\x03 \x01(\x05R\x0epreviousVolume\x12\x1d\n" +
	"\n" +
	"new_volume\x18\x04 \x01(\x05R\tnewVolume*3\n" +
	"\x06Engine\x12\x11\n" +
	"\rENGINE_SPIRIT\x10\x00\x12\x16\n" +
	"\x12ENGINE_PLANETSCALE\x10\x01*\xbe\x03\n" +
	"\x05State\x12\x1a\n" +
	"\x16STATE_NO_ACTIVE_CHANGE\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x02\x12\x1d\n" +
	"\x19STATE_WAITING_FOR_CUTOVER\x10\x03\x12\x16\n" +
	"\x12STATE_CUTTING_OVER\x10\x04\x12\x17\n" +
	"\x13STATE_REVERT_WINDOW\x10\x05\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x06\x12\x10\n" +
	"\fSTATE_FAILED\x10\a\x12\x11\n" +
	"\rSTATE_STOPPED\x10\b\x12\x12\n" +
	"\x0eSTATE_REVERTED\x10\t\x12\x13\n" +
	"\x0fSTATE_CANCELLED\x10\n" +
	"\x12\x1a\n" +
	"\x16STATE_PREPARING_BRANCH\x10\v\x12!\n" +
	"\x1dSTATE_APPLYING_BRANCH_CHANGES\x10\f\x12!\n" +
	"\x1dSTATE_CREATING_DEPLOY_REQUEST\x10\r\x12\x1c\n" +
	"\x18STATE_WAITING_FOR_DEPLOY\x10\x0e\x12#\n" +
	"\x1fSTATE_VALIDATING_DEPLOY_REQUEST\x10\x0f\x12\x1b\n" +
	"\x17STATE_VALIDATING_BRANCH\x10\x10*\x81\x01\n" +
	"\n" +
	"ChangeType\x12\x15\n" +
	"\x11CHANGE_TYPE_OTHER\x10\x00\x12\x16\n" +
	"\x12CHANGE_TYPE_CREATE\x10\x01\x12\x15\n" +
	"\x11CHANGE_TYPE_ALTER\x10\x02\x12\x14\n" +
	"\x10CHANGE_TYPE_DROP\x10\x03\x12\x17\n" +
	"\x13CHANGE_TYPE_VSCHEMA\x10\x042\xbc\x06\n" +
	"\x04Tern\x12H\n" +
	"\x04Plan\x12\x14.tern.v1.PlanRequest\x1a\x15.tern.v1.PlanResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/plan\x12L\n" +
	"\x05Apply\x12\x15.tern.v1.ApplyRequest\x1a\x16.tern.v1.ApplyResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/apply\x12X\n" +
	"\bProgress\x12\x18.tern.v1.ProgressRequest\x1a\x19.tern.v1.ProgressResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/progress\x12T\n" +
	"\aCutover\x12\x17.tern.v1.CutoverRequest\x1a\x18.tern.v1.CutoverResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/cutover\x12P\n" +
	"\x06Revert\x12\x16.tern.v1.RevertRequest\x1a\x17.tern.v1.RevertResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/revert\x12a\n" +
	"\n" +
	"SkipRevert\x12\x1a.tern.v1.SkipRevertRequest\x1a\x1b.tern.v1.SkipRevertResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/skip-revert\x12M\n" +
	"\x06Health\x12\x16.tern.v1.HealthRequest\x1a\x17.tern.v1.HealthResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12H\n" +
	"\x04Stop\x12\x14.tern.v1.StopRequest\x1a\x15.tern.v1.StopResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/stop\x12L\n" +
	"\x05Start\x12\x15.tern.v1.StartRequest\x1a\x16.tern.v1.StartResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/start\x12P\n" +
	"\x06Volume\x12\x16.tern.v1.VolumeRequest\x1a\x17.tern.v1.VolumeResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/volumeB-Z+github.com/block/schemabot/pkg/proto/ternv1b\x06proto3"

var (
	file_tern_proto_rawDescOnce sync.Once
	file_tern_proto_rawDescData []byte
)

func file_tern_proto_rawDescGZIP() []byte {
	file_tern_proto_rawDescOnce.Do(func() {
		file_tern_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tern_proto_rawDesc), len(file_tern_proto_rawDesc)))
	})
	return file_tern_proto_rawDescData
}

var file_tern_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tern_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_tern_proto_goTypes = []any{
	(Engine)(0),                // 0: tern.v1.Engine
	(State)(0),                 // 1: tern.v1.State
	(ChangeType)(0),            // 2: tern.v1.ChangeType
	(*SchemaFiles)(nil),        // 3: tern.v1.SchemaFiles
	(*PlanRequest)(nil),        // 4: tern.v1.PlanRequest
	(*TableChange)(nil),        // 5: tern.v1.TableChange
	(*SchemaChange)(nil),       // 6: tern.v1.SchemaChange
	(*LintViolation)(nil),      // 7: tern.v1.LintViolation
	(*PlanResponse)(nil),       // 8: tern.v1.PlanResponse
	(*ApplyRequest)(nil),       // 9: tern.v1.ApplyRequest
	(*ApplyResponse)(nil),      // 10: tern.v1.ApplyResponse
	(*ProgressRequest)(nil),    // 11: tern.v1.ProgressRequest
	(*ShardProgress)(nil),      // 12: tern.v1.ShardProgress
	(*TableProgress)(nil),      // 13: tern.v1.TableProgress
	(*ProgressResponse)(nil),   // 14: tern.v1.ProgressResponse
	(*CutoverRequest)(nil),     // 15: tern.v1.CutoverRequest
	(*CutoverResponse)(nil),    // 16: tern.v1.CutoverResponse
	(*RevertRequest)(nil),      // 17: tern.v1.RevertRequest
	(*RevertResponse)(nil),     // 18: tern.v1.RevertResponse
	(*SkipRevertRequest)(nil),  // 19: tern.v1.SkipRevertRequest
	(*SkipRevertResponse)(nil), // 20: tern.v1.SkipRevertResponse
	(*HealthRequest)(nil),      // 21: tern.v1.HealthRequest
	(*HealthResponse)(nil),     // 22: tern.v1.HealthResponse
	(*StopRequest)(nil),        // 23: tern.v1.StopRequest
	(*StopResponse)(nil),       // 24: tern.v1.StopResponse
	(*StartRequest)(nil),       // 25: tern.v1.StartRequest
	(*StartResponse)(nil),      // 26: tern.v1.StartResponse
	(*VolumeRequest)(nil),      // 27: tern.v1.VolumeRequest
	(*VolumeResponse)(nil),     // 28: tern.v1.VolumeResponse
	nil,                        // 29: tern.v1.SchemaFiles.FilesEntry
	nil,                        // 30: tern.v1.PlanRequest.SchemaFilesEntry
	nil,                        // 31: tern.v1.SchemaChange.MetadataEntry
	nil,                        // 32: tern.v1.ApplyRequest.OptionsEntry
	nil,                        // 33: tern.v1.ApplyRequest.SchemaFilesEntry
	nil,                        // 34: tern.v1.ProgressResponse.MetadataEntry
}
var file_tern_proto_depIdxs = []int32{
	29, // 0: tern.v1.SchemaFiles.files:type_name -> tern.v1.SchemaFiles.FilesEntry
	30, // 1: tern.v1.PlanRequest.schema_files:type_name -> tern.v1.PlanRequest.SchemaFilesEntry
	2,  // 2: tern.v1.TableChange.change_type:type_name -> tern.v1.ChangeType
	5,  // 3: tern.v1.SchemaChange.table_changes:type_name -> tern.v1.TableChange
	31, // 4: tern.v1.SchemaChange.metadata:type_name -> tern.v1.SchemaChange.MetadataEntry
	0,  // 5: tern.v1.PlanResponse.engine:type_name -> tern.v1.Engine
	6,  // 6: tern.v1.PlanResponse.changes:type_name -> tern.v1.SchemaChange
	7,  // 7: tern.v1.PlanResponse.lint_violations:type_name -> tern.v1.LintViolation
	32, // 8: tern.v1.ApplyRequest.options:type_name -> tern.v1.ApplyRequest.OptionsEntry
	33, // 9: tern.v1.ApplyRequest.schema_files:type_name -> tern.v1.ApplyRequest.SchemaFilesEntry
	5,  // 10: tern.v1.ApplyRequest.ddl_changes:type_name -> tern.v1.TableChange
	12, // 11: tern.v1.TableProgress.shards:type_name -> tern.v1.ShardProgress
	2,  // 12: tern.v1.TableProgress.change_type:type_name -> tern.v1.ChangeType
	1,  // 13: tern.v1.ProgressResponse.state:type_name -> tern.v1.State
	0,  // 14: tern.v1.ProgressResponse.engine:type_name -> tern.v1.Engine
	13, // 15: tern.v1.ProgressResponse.tables:type_name -> tern.v1.TableProgress
	34, // 16: tern.v1.ProgressResponse.metadata:type_name -> tern.v1.ProgressResponse.MetadataEntry
	3,  // 17: tern.v1.PlanRequest.SchemaFilesEntry.value:type_name -> tern.v1.SchemaFiles
	3,  // 18: tern.v1.ApplyRequest.SchemaFilesEntry.value:type_name -> tern.v1.SchemaFiles
	4,  // 19: tern.v1.Tern.Plan:input_type -> tern.v1.PlanRequest
	9,  // 20: tern.v1.Tern.Apply:input_type -> tern.v1.ApplyRequest
	11, // 21: tern.v1.Tern.Progress:input_type -> tern.v1.ProgressRequest
	15, // 22: tern.v1.Tern.Cutover:input_type -> tern.v1.CutoverRequest
	17, // 23: tern.v1.Tern.Revert:input_type -> tern.v1.RevertRequest
	19, // 24: tern.v1.Tern.SkipRevert:input_type -> tern.v1.SkipRevertRequest
	21, // 25: tern.v1.Tern.Health:input_type -> tern.v1.HealthRequest
	23, // 26: tern.v1.Tern.Stop:input_type -> tern.v1.StopRequest
	25, // 27: tern.v1.Tern.Start:input_type -> tern.v1.StartRequest
	27, // 28: tern.v1.Tern.Volume:input_type -> tern.v1.VolumeRequest
	8,  // 29: tern.v1.Tern.Plan:output_type -> tern.v1.PlanResponse
	10, // 30: tern.v1.Tern.Apply:output_type -> tern.v1.ApplyResponse
	14, // 31: tern.v1.Tern.Progress:output_type -> tern.v1.ProgressResponse
	16, // 32: tern.v1.Tern.Cutover:output_type -> tern.v1.CutoverResponse
	18, // 33: tern.v1.Tern.Revert:output_type -> tern.v1.RevertResponse
	20, // 34: tern.v1.Tern.SkipRevert:output_type -> tern.v1.SkipRevertResponse
	22, // 35: tern.v1.Tern.Health:output_type -> tern.v1.HealthResponse
	24, // 36: tern.v1.Tern.Stop:output_type -> tern.v1.StopResponse
	26, // 37: tern.v1.Tern.Start:output_type -> tern.v1.StartResponse
	28, // 38: tern.v1.Tern.Volume:output_type -> tern.v1.VolumeResponse
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_tern_proto_init() }
func file_tern_proto_init() {
	if File_tern_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tern_proto_rawDesc), len(file_tern_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tern_proto_goTypes,
		DependencyIndexes: file_tern_proto_depIdxs,
		EnumInfos:         file_tern_proto_enumTypes,
		MessageInfos:      file_tern_proto_msgTypes,
	}.Build()
	File_tern_proto = out.File
	file_tern_proto_goTypes = nil
	file_tern_proto_depIdxs = nil
}
