#!/bin/bash
set -euo pipefail

# Regenerate TEMPLATES.md from the current binary.
# Called by the pre-commit hook and by preview-gist.sh.
#
# Renders paired PR + CLI sections under shared headings,
# plus CLI-only sections for unique features.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
BINARY="$REPO_ROOT/bin/schemabot"

if [ ! -x "$BINARY" ]; then
    echo "error: bin/schemabot not found — run 'make build' first" >&2
    exit 1
fi

# Strip ANSI escape codes from CLI output for markdown rendering.
strip_ansi() {
    sed $'s/\033\\[[0-9;]*m//g'
}

# Shared awk function to wrap "--- SECTION NAME ---" lines into collapsible blocks
wrap_sections() {
    local code_fence="${1:-0}"
    awk -v use_code_fence="$code_fence" '
        /^--- [A-Z].* -+$/ {
            if (in_section) {
                if (use_code_fence) print "```"
                print "</details>"
                print ""
            }
            name = $0
            sub(/^--- /, "", name)
            sub(/ -+$/, "", name)
            n = split(name, words, " ")
            result = ""
            for (i = 1; i <= n; i++) {
                w = words[i]
                # Preserve short acronyms (PR, CLI, DDL, SQL, ETA, etc.)
                # but title-case normal words even if they arrive ALL CAPS
                bare = w
                prefix = ""
                suffix = ""
                # Strip leading paren and trailing paren/colon/punctuation
                if (substr(w,1,1) == "(") { prefix = "("; bare = substr(bare, 2) }
                last = substr(bare, length(bare))
                if (last == ")" || last == ":" || last == ",") { suffix = last; bare = substr(bare, 1, length(bare)-1) }
                # Preserve known acronyms, title-case everything else
                upper_bare = toupper(bare)
                if (upper_bare == "PR" || upper_bare == "CLI" || upper_bare == "DDL" || upper_bare == "SQL" || upper_bare == "ETA" || upper_bare == "ID" || upper_bare == "API") {
                    w = prefix upper_bare suffix
                } else if (upper_bare == "MYSQL") {
                    w = prefix "MySQL" suffix
                } else if (upper_bare == "VITESS") {
                    w = prefix "Vitess" suffix
                } else if (upper_bare == "VSCHEMA") {
                    w = prefix "VSchema" suffix
                } else {
                    w = prefix toupper(substr(bare,1,1)) tolower(substr(bare,2)) suffix
                }
                result = (result == "" ? w : result " " w)
            }
            # Generate a URL-safe anchor ID from the section name
            anchor = tolower(result)
            gsub(/[^a-z0-9 ]/, "", anchor)
            gsub(/ /, "-", anchor)
            print "<details>"
            print "<summary><a name=\"" anchor "\"></a><strong>" result "</strong></summary>"
            print ""
            if (use_code_fence) print "```"
            in_section = 1
            next
        }
        { print }
        END {
            if (in_section) {
                if (use_code_fence) print "```"
                print "</details>"
            }
        }
    '
}

SNAPSHOT="$REPO_ROOT/TEMPLATES.md"
cat > "$SNAPSHOT" <<'HEADER'
<!-- Generated by scripts/update-templates.sh — do not edit manually -->
# SchemaBot Templates

All templates rendered with sample data.

HEADER

# Helper: render a paired section with PR and CLI subsections
render_paired_section() {
    local heading="$1"
    local pr_type="$2"
    local cli_type="$3"

    echo "## ${heading}" >> "$SNAPSHOT"
    echo "" >> "$SNAPSHOT"

    echo "### PR Comments" >> "$SNAPSHOT"
    echo "" >> "$SNAPSHOT"
    "$BINARY" preview "$pr_type" 2>&1 | wrap_sections >> "$SNAPSHOT"
    echo "" >> "$SNAPSHOT"

    echo "### CLI Output" >> "$SNAPSHOT"
    echo "" >> "$SNAPSHOT"
    "$BINARY" preview "$cli_type" 2>&1 | strip_ansi | wrap_sections 1 >> "$SNAPSHOT"
    echo "" >> "$SNAPSHOT"
}

# Helper: render a CLI-only section
render_cli_section() {
    local heading="$1"
    local preview_type="$2"

    echo "" >> "$SNAPSHOT"
    echo "## ${heading}" >> "$SNAPSHOT"
    echo "" >> "$SNAPSHOT"
    "$BINARY" preview "$preview_type" 2>&1 | strip_ansi | wrap_sections 1 >> "$SNAPSHOT"
    echo "" >> "$SNAPSHOT"
}

# === Paired sections (PR + CLI) ===
render_paired_section "Plan & Status"  "comment_plan_all"       "cli_plan_all"
render_paired_section "Locking"        "comment_locking_all"    "cli_locking_all"
render_paired_section "Apply Flow"     "comment_apply_flow_all" "cli_apply_all"

# === PR-only sections ===
{
    echo ""
    echo "## Apply Gates"
    echo ""
    echo "### PR Comments"
    echo ""
    "$BINARY" preview "comment_apply_all" 2>&1 | wrap_sections >> "$SNAPSHOT"
}

# === CLI-only sections ===
render_cli_section "Sequential Mode (CLI)" "sequential_all"
render_cli_section "Defer Cutover (CLI)"   "defer_all"
render_cli_section "Lint & Unsafe (CLI)"   "lint_all"
render_cli_section "Exit Context (CLI)"    "exit_all"
