CREATE TABLE `tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `task_identifier` varchar(255) NOT NULL,
  `apply_id` bigint unsigned NOT NULL,
  `plan_id` bigint unsigned NOT NULL,
  `database_name` varchar(255) NOT NULL,
  `database_type` varchar(50) NOT NULL,
  `namespace` varchar(255) NOT NULL DEFAULT '',
  `table_name` varchar(255) DEFAULT NULL,
  `ddl` text,
  `ddl_action` varchar(50) DEFAULT NULL,
  `engine` varchar(50) NOT NULL,
  `repository` varchar(255) NOT NULL,
  `pull_request` int unsigned NOT NULL,
  `environment` varchar(50) NOT NULL,
  `state` varchar(100) NOT NULL,
  `error_message` text,
  `options` json DEFAULT NULL,
  `attempt` int NOT NULL DEFAULT '0',
  `rows_copied` bigint DEFAULT '0',
  `rows_total` bigint DEFAULT '0',
  `progress_percent` int DEFAULT '0',
  `eta_seconds` int DEFAULT NULL,
  `is_instant` tinyint(1) DEFAULT '0',
  `ready_to_complete` tinyint(1) DEFAULT '0',
  `engine_migration_id` varchar(255) DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_task_identifier` (`task_identifier`),
  KEY `idx_apply_id` (`apply_id`),
  KEY `idx_database` (`database_name`),
  KEY `idx_repo_pr` (`repository`,`pull_request`),
  KEY `idx_state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
